file(GLOB_RECURSE SRC_FILES RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} src/*.cpp src/*.h)

file(GLOB_RECURSE SRC_THIRDPARTIES RELATIVE ${CMAKE_CURRENT_SOURCE_DIR}
ThirdParties/*.cpp ThirdParties/*.h ThirdParties/*.hpp ThirdParties/*.cxx)

file(GLOB_RECURSE JSON_FILES RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} Contents/*.json)

file(GLOB_RECURSE LUA_FILES RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} Contents/*.lua)

